services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: banking_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - banking_network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: banking_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - banking_network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: banking_kafka_ui
    depends_on:
      - kafka
    ports:
      - "8082:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - banking_network

  postgres:
    image: postgres:15
    container_name: banking_postgres
    environment:
      POSTGRES_DB: banking_system
      POSTGRES_USER: banking_user
      POSTGRES_PASSWORD: banking_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - banking_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: banking_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@banking.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - banking_network

  banking-app:
    build: .
    container_name: banking_app
    ports:
      - "8080:8080"
      - "8083:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=datadog
      - DATABASE_URL=jdbc:postgresql://postgres:5432/banking_system
      - DATABASE_USERNAME=banking_user
      - DATABASE_PASSWORD=banking_password
      - KAFKA_SERVERS=kafka:9092
      - APP_NAME=Banking System Application
      - APP_VERSION=1.0.0
      - APP_ENVIRONMENT=docker
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
      # Datadog Configuration
      - DD_SERVICE=banking-system
      - DD_ENV=docker
      - DD_VERSION=1.0.0
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=us5.datadoghq.com
      - DD_LOGS_INJECTION=true
      - DD_TRACE_SAMPLE_RATE=1
      - DD_PROFILING_ENABLED=true
      - DD_AGENT_HOST=localhost
      - DD_TRACE_AGENT_PORT=8126
      # Disable OpenTelemetry auto-instrumentation to avoid compatibility issues
      - OTEL_JAVAAGENT_ENABLED=false
      - OTEL_SDK_DISABLED=true
      # Performance optimizations
      - JAVA_OPTS=-Xms512m -Xmx2g -XX:+UseG1GC -XX:MaxGCPauseMillis=100
    depends_on:
      - postgres
      - kafka
    networks:
      - banking_network

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: banking_zipkin
    ports:
      - "9411:9411"
    networks:
      - banking_network

volumes:
  postgres_data:

networks:
  banking_network:
    driver: bridge